FORUM_WEB_2.0/Controllers/PostPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FORUM_WEB_2._0.Models.FrameWorks;
using FORUM_WEB_2._0.Models;
using System.IO;

namespace FORUM_WEB_2._0.Controllers
{
    public class PostPageController : Controller
    {
        int id;
        Models.FrameWorks.FORUM_WEB_V2Entities db = new Models.FrameWorks.FORUM_WEB_V2Entities();
        // GET: PostPage
        public ActionResult PostPage(int id)
        {
            this.id = id;
            var post = db.BaiDang.Where(x => x.ID_BaiDang == id).FirstOrDefault();
            return View(post);
        }
        
        public ActionResult Comment(int id)
        {
            var lst = new List<FORUM_WEB_2._0.Models.FrameWorks.BinhLuan>();
            lst = db.BinhLuan.Where(x => x.ID_BaiDang == id).ToList();
            return PartialView(lst);
        }
        public ActionResult PostComment()
        {

            return PartialView();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult PostComment(CommentModel model, int id, List<HttpPostedFileBase> image)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[FORUM_WEB_2._0.Common.CommonSession.USER_LOGIN];
                var comment = new BinhLuan()
                {
                    NoiDung = model.NoiDung,
                    TenDangNhap = session.TenDangNhap,
                    NgayBinhLuan = DateTime.Now,
                    ID_BaiDang = id
                };
                string path = Server.MapPath("~/Asset/img/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                foreach (HttpPostedFileBase pFile in image)
                {
                    /*var f = Request.Files["image"];
                    string path = Server.MapPath("~/Asset/img/" + f.FileName);
                    f.SaveAs(path);*/

                    if (pFile != null)
                    {
                        string fileName = Path.GetFileName(pFile.FileName);
                        pFile.SaveAs(path + fileName);
                        var Img_Comment = new Img_BinhLuan()
                        {
                            ID_BinhLuan = comment.ID_BinhLuan,
                            TenAnh_Img_BinhLuan = pFile.FileName
                        };
                        db.Img_BinhLuan.Add(Img_Comment);
                    }
                }
                db.BinhLuan.Add(comment);
                db.SaveChanges();
                return Redirect(Request.UrlReferrer.ToString());
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
        public ActionResult PostThread()
        {
            return View();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult PostThread(ThreadModel model, int id, List<HttpPostedFileBase> postedFiles)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[FORUM_WEB_2._0.Common.CommonSession.USER_LOGIN];
                var thread = new BaiDang()
                {
                    TieuDe = model.TieuDe,
                    NoiDung = model.NoiDung,
                    ID_ChuDe = id,
                    TenDangNhap = session.TenDangNhap,
                    NgayDangBai = DateTime.Now
                };
                string path = Server.MapPath("~/Asset/img/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                foreach (HttpPostedFileBase pFile in postedFiles)
                {
                    /*var f = Request.Files["image"];
                    string path = Server.MapPath("~/Asset/img/" + f.FileName);
                    f.SaveAs(path);*/

                    if (pFile != null)
                    {
                        string fileName = Path.GetFileName(pFile.FileName);
                        pFile.SaveAs(path + fileName);
                        var Img_Post = new Img_BaiDang()
                        {
                            ID_BaiDang = thread.ID_BaiDang,
                            TenAnh_Img_BaiDang = pFile.FileName
                        };
                        db.Img_BaiDang.Add(Img_Post);
                    }
                }

                db.BaiDang.Add(thread);
                db.SaveChanges();
                return RedirectToAction("ThreadPage", "ThreadPage", new { id = id });
            }
            return View();
        }
        public ActionResult Img_Post(int id)
        {
            var lst = new List<FORUM_WEB_2._0.Models.FrameWorks.Img_BaiDang>();
            lst = db.Img_BaiDang.Where(x => x.ID_BaiDang == id).ToList();
            return PartialView(lst);
        }
        public ActionResult Img_Comment(int id_comment)
        {
            var lst = new List<FORUM_WEB_2._0.Models.FrameWorks.Img_BinhLuan>();
            lst = db.Img_BinhLuan.Where(x => x.ID_BinhLuan == id_comment).ToList();
            return PartialView(lst);
        }
        public ActionResult Delete_Post(int id)
        {
            BaiDang baiDang = db.BaiDang.Find(id);
            db.BaiDang.Remove(baiDang);
            db.SaveChanges();
            return RedirectToAction("ThreadPage","ThreadPage", new { id = id });
        }
        public ActionResult Delete_Comment(int id_comment)
        {
            BinhLuan binhLuan = db.BinhLuan.Find(id_comment);
            db.BinhLuan.Remove(binhLuan);
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }
        [HttpPost]
        public ActionResult Edit_Post(ThreadModel model, int id)
        {
            BaiDang baiDang = db.BaiDang.Find(id);
            baiDang.TieuDe = model.TieuDe;
            baiDang.NoiDung = model.NoiDung;
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }
        /*[HttpGet]
        public ActionResult Edit_Comment(int id_comment)
        {
            BinhLuan binhLuan = db.BinhLuan.Find(id_comment);
            return View(binhLuan);
        }*/
        [HttpPost]
        public ActionResult Edit_Comment(CommentModel model, int id_comment)
        {
            BinhLuan binhLuan = db.BinhLuan.Where(x => x.ID_BinhLuan == id_comment).FirstOrDefault();
            binhLuan.NoiDung = model.NoiDung;
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

FORUM_WEB_2.0/Controllers/ThreadPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
namespace FORUM_WEB_2._0.Controllers
{
    public class ThreadPageController : Controller
    {
        // GET: ThreadPage
        public ActionResult ThreadPage(int id, int? page)
        {
            ViewBag.id_cd = id;
            if (page == null) page = 1;
            int pageSize = 15;
            int pageNumber = (page ?? 1);
            Models.FrameWorks.FORUM_WEB_V2Entities db = new Models.FrameWorks.FORUM_WEB_V2Entities();
            var lst = new List<Models.FrameWorks.BaiDang>();
            lst = db.BaiDang.Where(x => x.ID_ChuDe == id).ToList();
            return View((lst.ToPagedList(pageNumber, pageSize)));
        }
    }
}

FORUM_WEB_2.0/Views/ThreadPage/ThreadPage.cshtml
@model PagedList.IPagedList<FORUM_WEB_2._0.Models.FrameWorks.BaiDang>
@using PagedList.Mvc
@using PagedList
@{
    ViewBag.Title = "ThreadPage";
    Layout = "~/Views/Shared/my_Layout.cshtml";
}
@section styles{
    <style>
        .thread-func {
            display: flex;
            justify-content: space-between;
        }

        .avatar {
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .col3 {
            display: flex;
            justify-content: space-around;
        }

        .question {
            border-bottom: solid 1px #d3d5d7;
        }

        .navigate > a {
            color: white;
        }
    </style>
}

<div class="container" style="padding: 0;">
    <div class="header-thread">
        @{
            var TieuDe = "";
            if (Model.Count > 0)
            {
                TieuDe = Model.FirstOrDefault().ChuDe.TenChuDe;
            }
            else
            {
                TieuDe = "Không có bài đăng!";
            }
            <div class="thread-name">
                <h4 style="color: white; font-weight: 400;">@TieuDe</h4>
            </div>
        }
        <div class="thread-func">
            <div class="navigation-page">
                <div style="">
                    @if ((Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) == 1)
                    {
                        <div style="margin: 10px; float: left; ">

                        </div>
                    }
                    else
                    {
                        <div style="margin: 10px; float: left">
                            @Html.ActionLink("<<", "Index", new { page = 1 }, new { @style = "color:white;" })
                        </div>
                        <div style="margin: 10px; float: left ">
                            <a style="color: white;" href="@Url.Action("Index",new { page = (Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber - 1) })"> @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber -1 )</a>
                        </div>
                    }
                    <div style="margin: 10px; float: left;color:#ff3838 ">
                        @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                    </div>
                    @if ((Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) == Model.PageCount)
                    {
                        <div style="margin: 10px; float: left ">

                        </div>
                    }
                    else
                    {
                        <div style="margin: 10px; float: left ">
                            <a style="color: white;" href="@Url.Action("Index",new { page = (Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber + 1) })"> @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber +1 )</a>
                        </div>
                        <div style="margin: 10px; float: left ">
                            @Html.ActionLink(">>", "Index", new { page = Model.PageCount }, new { @style = "color:white;" })
                        </div>
                    }
                </div>
            </div>
            <div class="post-thread">
                <button type="button" class="btn btn-danger btn-post">
                    <ion-icon name="create-outline"></ion-icon>
                    <a href="@Url.Action("PostThread", "PostPage", new {id = ViewBag.id_cd})" style="color: white; text-decoration: none;"><span>Post Thread</span></a>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="container" style=" margin-top: 20px; background-color: #ebeced;">
    @{
        foreach (var item2 in Model)
        {
            <div class="row question">
                <div class="col-xl-1" style="display:flex;align-items: center; justify-content: center;">
                    <div class="avatar">
                        <img src="~/Asset/img/@item2.TaiKhoan.Avatar" alt="" style="width: 40px; height: 40px; border-radius: 50%;">
                    </div>
                </div>
                <div class="col-xl-6" style="display:flex;align-items: center;">
                    <div class="tittle-question">
                        <a href="@Url.Action("PostPage","PostPage",new {id = item2.ID_BaiDang}) "><span style="color: #23497c;">@Html.Raw(item2.TieuDe)</span></a>
                    </div>
                </div>
                <div class="col-xl-3" style="display:flex;align-items: center; justify-content: center;">
                    <div class="col3">
                        <div>
                            <span style="color: #8f91aa;">Replies: </span>
                        </div>
                        <div>
                            <span>@item2.BinhLuan.Count()</span>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2" style="display:flex;align-items: center; justify-content: center;">
                    <div>
                        <h5 style="color: #8f91aa;">@item2.NgayDangBai</h5>
                    </div>
                </div>
            </div>
        }
    }

</div>